# Generated by Django 4.0.5 on 2022-08-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='image',
            field=models.ImageField(null=True, upload_to='islands/'),
        ),
    ]
